### ISSUE TITLE
Timeseries selection modal

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-catalogue#192]
A modal to select timeseries that belong to a measuring network. Some main points to take into consideration:

- Map with locations of the timeseries - done
- Filter with observation types - done
- Search bar - done
- Duration/period - done
- Selection list - done
- Export functionality to xlsx - done
- Open in API/Lizard - done

**Comment by hoanphungt** [comment]
@lexvand @byrman 
The timeseries selection modal requires some filters on timeseries endpoint:

1. start - end
2. observation type
3. location name
4. maybe more but I don't know yet

Could you check if these filters have been support by the API?

**Comment by lexvand** [comment]
See: https://nxt3.staging.lizard.net/api/v4/timeseries/

Start(__gte)/end(__lte) is not supported yet. See: https://github.com/nens/lizard-nxt/issues/4372

**Comment by hoanphungt** [comment]
@lexvand 
Sorry, maybe I misunderstand it but I thought I need the filters for this timeseries endpoint: https://nxt3.staging.lizard.net/api/v4/monitoringnetworks/10cc70a4-6d02-440a-99d6-820b90e86f52/timeseries/, not the one you mentioned

**Comment by Derryrover** [comment]
@hoanphungt 
@lexvand 
@remcogerlich 
@joeriverheijden 
@LirryPinter 


Hi Hoan, Lex, Remco, Lirry and Joeri,

I am currently reviewing the branch of Hoan.
I think it looks overall good in terms of code quality.
Therefore my compliments !

Anyway, I do experience some difficulties with reviewing the catalog in general.
In order for me to evaluate the: functionality, data model (within redux + within react), ux, css, bugs, I would need to significantly spend more time on this, but I feel I do not have this time right now. 
There are several aspects of the catalogue that concern me (most not new to this pr) including:
- One big reducer
- Doubtful coherence what lives in redux versus what lives in react.
- Doubtfull coherence what can be accessed via url versus what only lives in app state
- etcetera

I am missing the oversight in this app to know what is handy versus not handy.
At this moment it seems we are going to develop this product further.
I think we need a review on the complete architecture.
I am not saying the current architecture is bad or the latest changes are bad,
but I am just saying that I find it difficult to evaluate this within reasonable time (within half a day) at the moment.

Since the catalog is at the moment not a very big product a mediocre architecture is not such a big risk.
Anyway we keep ourselves busy adding more features and within a year we will have another product that becomes challanging to maintain. 
I like to hear your opinion on the questions that concern you:
-  Do you feel you have oversight on this app?
- Are you in agreement of the architecture choices?
- How far can we let this grow without a refactor?
- How far does the business expects this to grow?
- How is the usability so far?

Please answer in this ticket if you can.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I agree if we want to develop the Lizard Catalogue further (for example by adding new features, new filters, new data models ...), it would be a good idea to review the architecture and refactor some parts before going further. The parts I think would be most beneficial are as below:

- Reducer
- Action
(currently both 1 big reducer and 1 big action files, but we can separate them into smaller ones in ducks pattern like in the live-site)

- Review the Redux store, React state and URL state. Currently, the URL is kept in sync with the filter state in Redux. For Redux store, I mostly kept only stuffs that we need access in more than 2 components. For data that only used in one component then I keep in React state.

- Refactor class based components to functional based components using React Hooks
- Refactor the MainApp.tsx. This MainApp.tsx contains a lot of logics about how and when to fetch different datas. It's overly complicated in my opinion especially all the component life cycles methods (componentDidMount, componentWillUpdate, etc). It might already be better if we refactor is to become functional component using useEffect instead.
- Review the overall architecture of the App.

That's all I can think of for now.
