### ISSUE TITLE
Loading monitoring network with lots of locations sometimes gives 504 (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-catalogue#246]
#### What went wrong?
Sometimes when you press on the select time series action (for timeseries), the loading screen crashes.

#### What did you do in which order?
Select a timeseries, 'Large N&S sample' in this case.
Select 'Select time series' from the actions.
The loading screen shows, but it hangs on the loading screen.

#### Who noticed it?
Internal

### Noticed where
Staging:
https://nxt3.staging.lizard.net/catalogue/?data=Timeseries&uuid=0026cda8-5497-4496-9a76-1c18b81c895c

### Used browser
Chrome (default for testing)

### Screenshot

![20210113-catalogue-staging-monitoring-network-locations-pagesize-10000-gives-504-error.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/454ccc98-2a9c-48fe-bc14-8ccdf6dae117)

![20210113-catalogue-staging-monitoring-network-locations-pagesize-10000-gives-504-error-2.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/4a2874b8-3c69-4e81-a25a-38238a2bab7c)

![20210113-catalogue-staging-monitoring-network-locations-pagesize-10000-gives-504-error-3.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/1b7e87d6-4d02-47d5-bfc0-4c7766868205)

Good luck!

**Comment by hoanphungt** [comment]
While working on https://github.com/nens/lizard-catalogue/issues/280, this issue is resolved by:

- change the page_size query from `page_size=10000` to `page_size=100` for the timeseries api call and use a recursive fetch function to build all the timeseries records (so for 5000 timeseries, 50 requests with page_size=100 will be sent to the server instead of 1 request with page_size=10000). You still have to wait for the loading screen for quite long (~ 1 minute) but it's no longer time out and produce results consistently.

- When the API request fails or is timeout in the background, a notification will be displayed to inform users that it failed to retrieve the timeseries. This notification is also used for other places when the API request fails.

**Comment by lexvand** [comment]
@hoanphungt So, on the main page, when selecting a monitoring network I see a page size of 1000 for the preview of locations on the map in the top right corner. In the modal the locations are retrieved again, but then in batches of 100. 

The solution seems to prevent timeouts, which is good. I still think we should improve this by limiting the number of fetched locations, maybe make it more bbox related, maybe present in in a more aggregated way in the client (like e.g. events in Lizard client) and indicate this behaviour to the user. Especially for very large networks it is still problematic to visualise properly.

**Comment by hoanphungt** [comment]
@lexvand 
That's right. When you use a filter in the timeseries selection modal, the page size request query for location is 100. I assume that when you use a filter, you don't expect to see 1000s of locations in your result.

I think this is only a temporary solution for this timeout case. A long-term solution is still needed and there is a ticket for it: https://github.com/nens/lizard-catalogue/issues/283.
